### ISSUE TITLE
Game: eternaljk

### ISSUE THREAD

**Issue by tallyie** [eternalcodes/EternalJK#59] opened 2018-02-10 03:46 UTC
even in your latest build, you still didn't remove the game filter on the browser. eternaljk isn't a mod. it's a client, and a very buggy one to say the least. please remove this and add japro or mb2 or something.

**Comment by eternalcodes** [comment] 2018-02-11 04:23
duplicate of #67

**Closed by eternalcodes** 2018-02-11 04:23 UTC
